server:
  servlet:
    context-path: /car
spring: 
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.222.136:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false 


# Redis数据库索引（默认为0）  
  redis: 
    database: 0
# Redis服务器地址   
    host: 192.168.222.136
# Redis服务器连接端口  
    port: 6385
# Redis服务器连接密码（默认为空）  
    #password:
# 连接池最大连接数（使用负值表示没有限制）  
    pool: 
      max-active: 200
# 连接池最大阻塞等待时间（使用负值表示没有限制）  
      max-wait: -1
# 连接池中的最大空闲连接  
      max-idle: 10
# 连接池中的最小空闲连接  
      min-idle: 0
# 连接超时时间（毫秒）  
    timeout: 1000
    
    
mybatis: 
  mapperLocations: classpath*:com.hh.wx.xcx.service.mapper/*.xml
wx: 
  appid: wxae3b0295ff461c7e
  secret: 1ae483b279848974abf529250710df5f
  session-url: https://api.weixin.qq.com/sns/jscode2session